name: Random Blockchain

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  random_blockchain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run random blockchain and save output
      run: |
        go run main.go > output.txt

    - name: Commit and push output file
      env:
        GITHUB_TOKEN: ${{ secrets.R_TOKEN }}
      run: |
        git config --local user.email "mirlok@dr.com"
        git config --local user.name "m1rl0k"
        git add output.txt
        git commit -m "Add output.txt file" || echo "Commit output of random_blockchain github action to output.txt"
        git push
