name: Random Blockchain

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  random_blockchain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run random blockchain and save output
      run: |
        go run *.go
